import os
import anthropic
import requests

# Configuration
ANTHROPIC_API_KEY = os.environ['ANTHROPIC_API_KEY']
GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
GITHUB_REPO = os.environ['GITHUB_REPOSITORY']
ISSUE_NUMBER = os.environ['ISSUE_NUMBER']

def get_issue_details():
    """Fetch issue details from GitHub"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{ISSUE_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    response = requests.get(url, headers=headers)
    return response.json()

def analyze_requirements(issue_title, issue_body):
    """Use Claude to analyze requirements and create structured specification"""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    
    prompt = f"""You are a Business Analyst AI agent. Analyze this requirement and create a detailed specification.

**Requirement:**
Title: {issue_title}
Description: {issue_body or 'No description provided'}

**Your task:**
Create a comprehensive analysis with:
1. User Stories (As a [user], I want [goal], so that [benefit])
2. Acceptance Criteria (Given/When/Then format)
3. Technical Specifications (API endpoints, data models, etc.)
4. Dependencies and assumptions
5. Estimated complexity (S/M/L/XL)

Format your response as a well-structured markdown document."""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}]
    )
    
    return message.content[0].text

def update_issue(analysis):
    """Update the GitHub issue with BA analysis"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{ISSUE_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    
    # Add BA analysis as a comment
    comment_url = f"{url}/comments"
    comment_body = {
        "body": f"## 📋 BA Agent Analysis\n\n{analysis}\n\n---\n*Generated by BA Agent*"
    }
    
    response = requests.post(comment_url, headers=headers, json=comment_body)
    
    if response.status_code == 201:
        print(f"✅ Comment posted successfully")
    else:
        print(f"⚠️ Comment posting failed: {response.status_code}")
    
    # Add labels
    labels_data = {"labels": ["analyzed", "ready-for-dev"]}
    requests.post(f"{url}/labels", headers=headers, json=labels_data)
    
    print(f"✅ Issue #{ISSUE_NUMBER} updated with BA analysis")

def main():
    print(f"🤖 BA Agent starting for issue #{ISSUE_NUMBER}...")
    
    # Get issue details
    issue = get_issue_details()
    print(f"📖 Analyzing: {issue['title']}")
    
    # Analyze with Claude
    analysis = analyze_requirements(issue['title'], issue.get('body', ''))
    print(f"✅ Analysis complete ({len(analysis)} characters)")
    
    # Update issue
    update_issue(analysis)
    print("✅ BA Agent completed successfully!")

if __name__ == "__main__":
    main()
