import os
import anthropic
import requests
import time

# Configuration
ANTHROPIC_API_KEY = os.environ['ANTHROPIC_API_KEY']
GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
GITHUB_REPO = os.environ['GITHUB_REPOSITORY']
ISSUE_NUMBER = os.environ['ISSUE_NUMBER']
NOTION_TOKEN = os.environ.get('NOTION_TOKEN')  # Original token for BA results
NOTION_TOKEN_TRIGGER = os.environ.get('NOTION_TOKEN_TRIGGER')  # Separate token for trigger database
NOTION_DATABASE_ID = os.environ.get('NOTION_DATABASE_ID')
NOTION_METRICS_DB_ID = os.environ.get('NOTION_METRICS_DB_ID')
NOTION_TRIGGER_DB_ID = os.environ.get('NOTION_TRIGGER_DB_ID')  # NEW: Database for Notion-triggered issues

# Normalize database IDs (remove dashes if present)
if NOTION_DATABASE_ID:
    NOTION_DATABASE_ID = NOTION_DATABASE_ID.replace('-', '')
if NOTION_METRICS_DB_ID:
    NOTION_METRICS_DB_ID = NOTION_METRICS_DB_ID.replace('-', '')
if NOTION_TRIGGER_DB_ID:
    clean_id = NOTION_TRIGGER_DB_ID.replace('-', '').strip()
    if len(clean_id) == 32:
        NOTION_TRIGGER_DB_ID = f"{clean_id[0:8]}-{clean_id[8:12]}-{clean_id[12:16]}-{clean_id[16:20]}-{clean_id[20:32]}"

# Metrics tracking
start_time = time.time()
tokens_used = 0

def get_issue_details():
    """Fetch issue details from GitHub"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{ISSUE_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    response = requests.get(url, headers=headers)
    return response.json()

def analyze_requirements(issue_title, issue_body):
    """Use Claude to analyze requirements and create structured specification"""
    global tokens_used
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    
    prompt = f"""You are a Business Analyst AI agent. Analyze this requirement and create a detailed specification.

**Requirement:**
Title: {issue_title}
Description: {issue_body or 'No description provided'}

**Your task:**
Create a comprehensive analysis with:
1. User Stories (As a [user], I want [goal], so that [benefit])
2. Acceptance Criteria (Given/When/Then format)
3. Technical Specifications (API endpoints, data models, etc.)
4. Dependencies and assumptions
5. Estimated complexity (S/M/L/XL)

Format your response as a well-structured markdown document."""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}]
    )
    
    # Track token usage
    tokens_used = message.usage.input_tokens + message.usage.output_tokens
    
    return message.content[0].text

def update_issue(analysis):
    """Update the GitHub issue with BA analysis"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{ISSUE_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    
    # Add BA analysis as a comment
    comment_url = f"{url}/comments"
    comment_body = {
        "body": f"## 📋 BA Agent Analysis\n\n{analysis}\n\n---\n*Generated by BA Agent*"
    }
    
    response = requests.post(comment_url, headers=headers, json=comment_body)
    
    if response.status_code == 201:
        print(f"✅ Comment posted successfully")
    else:
        print(f"⚠️ Comment posting failed: {response.status_code}")
    
    # Add labels
    labels_data = {"labels": ["analyzed", "ready-for-dev"]}
    requests.post(f"{url}/labels", headers=headers, json=labels_data)
    
    print(f"✅ Issue #{ISSUE_NUMBER} updated with BA analysis")

def post_to_notion(issue_title, issue_number, analysis):
    """Post BA analysis to Notion database"""
    if not NOTION_TOKEN or not NOTION_DATABASE_ID:
        print("⚠️ Notion credentials not configured, skipping Notion post")
        return
    
    headers = {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }
    
    # Truncate analysis if too long (Notion has limits)
    truncated_analysis = analysis[:1900] if len(analysis) > 1900 else analysis
    
    data = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Name": {
                "title": [{"text": {"content": f"BA Analysis: {issue_title[:80]}"}}]
            },
            "Agent Type": {
                "select": {"name": "BA"}
            },
            "Issue/PR Number": {
                "number": int(issue_number)
            },
            "Status": {
                "select": {"name": "Complete"}
            }
        },
        "children": [
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"type": "text", "text": {"content": "Business Analysis"}}]
                }
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [{"type": "text", "text": {"content": truncated_analysis}}]
                }
            }
        ]
    }
    
    response = requests.post(
        "https://api.notion.com/v1/pages",
        headers=headers,
        json=data
    )
    
    if response.status_code == 200:
        print(f"✅ Posted to Notion successfully!")
    else:
        print(f"⚠️ Notion post failed: {response.status_code}")
        print(response.text)

def add_analysis_to_notion_page(page_id, analysis):
    """Append BA analysis to an existing Notion page"""
    if not NOTION_TOKEN_TRIGGER:
        return
    
    headers = {
        "Authorization": f"Bearer {NOTION_TOKEN_TRIGGER}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }
    
    # Truncate if needed
    truncated_analysis = analysis[:1900] if len(analysis) > 1900 else analysis
    
    # Add blocks to the page
    data = {
        "children": [
            {
                "object": "block",
                "type": "divider",
                "divider": {}
            },
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"type": "text", "text": {"content": "📋 BA Agent Analysis"}}]
                }
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [{"type": "text", "text": {"content": truncated_analysis}}]
                }
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {"type": "text", "text": {"content": "View full issue on GitHub: "}},
                        {
                            "type": "text",
                            "text": {"content": f"Issue #{ISSUE_NUMBER}"},
                            "annotations": {"bold": True}
                        }
                    ]
                }
            }
        ]
    }
    
    response = requests.patch(
        f"https://api.notion.com/v1/blocks/{page_id}/children",
        headers=headers,
        json=data
    )
    
    if response.status_code == 200:
        print(f"✅ Added analysis to original Notion page")
    else:
        print(f"⚠️ Failed to add analysis to Notion page: {response.status_code}")

def update_original_notion_page(analysis):
    """Update the Notion page that triggered this GitHub issue"""
    if not NOTION_TOKEN_TRIGGER or not NOTION_TRIGGER_DB_ID:
        print("⚠️ Notion trigger database not configured, skipping original page update")
        return
    
    try:
        headers = {
            "Authorization": f"Bearer {NOTION_TOKEN_TRIGGER}",
            "Content-Type": "application/json",
            "Notion-Version": "2022-06-28"
        }
        
        # Query for the Notion page with this GitHub issue number
        query_data = {
            "filter": {
                "property": "GitHub Issue Number",
                "number": {
                    "equals": int(ISSUE_NUMBER)
                }
            }
        }
        
        response = requests.post(
            f"https://api.notion.com/v1/databases/{NOTION_TRIGGER_DB_ID}/query",
            headers=headers,
            json=query_data
        )
        
        if response.status_code == 200:
            results = response.json().get('results', [])
            
            if results:
                page_id = results[0]['id']
                print(f"📄 Found original Notion page, updating...")
                
                # Update the status to "Analyzed"
                update_data = {
                    "properties": {
                        "Status": {
                            "select": {"name": "Analyzed"}
                        }
                    }
                }
                
                requests.patch(
                    f"https://api.notion.com/v1/pages/{page_id}",
                    headers=headers,
                    json=update_data
                )
                
                # Add the analysis to the page
                add_analysis_to_notion_page(page_id, analysis)
            else:
                print("ℹ️ No matching Notion page found (issue not created from Notion)")
        else:
            print(f"⚠️ Failed to query Notion: {response.status_code}")
    
    except Exception as e:
        print(f"⚠️ Error updating original Notion page: {e}")

def log_metrics(status="Success", error_message=None):
    """Log performance metrics to Notion"""
    if not NOTION_TOKEN or not NOTION_METRICS_DB_ID:
        print("⚠️ Metrics database not configured, skipping metrics logging")
        return
    
    execution_time = round(time.time() - start_time, 2)
    
    # Calculate cost (Claude Sonnet 4 pricing)
    input_cost = (tokens_used * 0.7) * (3.00 / 1_000_000)
    output_cost = (tokens_used * 0.3) * (15.00 / 1_000_000)
    cost = round(input_cost + output_cost, 4)
    
    headers = {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }
    
    properties = {
        "Name": {
            "title": [{"text": {"content": f"BA - Issue #{ISSUE_NUMBER}"}}]
        },
        "Agent": {"select": {"name": "BA"}},
        "Execution Time": {"number": execution_time},
        "Tokens Used": {"number": tokens_used},
        "Cost": {"number": cost},
        "Status": {"select": {"name": status}},
        "Issue/PR Number": {"number": int(ISSUE_NUMBER)}
    }
    
    if error_message:
        properties["Error Message"] = {
            "rich_text": [{"text": {"content": str(error_message)[:2000]}}]
        }
    
    data = {
        "parent": {"database_id": NOTION_METRICS_DB_ID},
        "properties": properties
    }
    
    try:
        response = requests.post(
            "https://api.notion.com/v1/pages",
            headers=headers,
            json=data,
            timeout=10
        )
        
        if response.status_code == 200:
            print(f"📊 Metrics logged: {execution_time}s, {tokens_used} tokens, ${cost}")
        else:
            print(f"⚠️ Metrics logging failed: {response.status_code}")
    except Exception as e:
        print(f"⚠️ Metrics error: {e}")

def main():
    print(f"🤖 BA Agent starting for issue #{ISSUE_NUMBER}...")
    
    try:
        # Get issue details
        issue = get_issue_details()
        print(f"📖 Analyzing: {issue['title']}")
        
        # Analyze with Claude
        analysis = analyze_requirements(issue['title'], issue.get('body', ''))
        print(f"✅ Analysis complete ({len(analysis)} characters)")
        
        # Update GitHub
        update_issue(analysis)
        
        # Post to Notion (regular BA database)
        print("📝 Posting to Notion...")
        post_to_notion(issue['title'], ISSUE_NUMBER, analysis)
        
        # NEW: Update the original Notion page that triggered this issue (if it exists)
        print("🔄 Checking for original Notion page...")
        update_original_notion_page(analysis)
        
        # Log metrics
        log_metrics(status="Success")
        
        print("✅ BA Agent completed successfully!")
        
    except Exception as e:
        print(f"❌ BA Agent failed: {e}")
        log_metrics(status="Failed", error_message=str(e))
        raise

if __name__ == "__main__":
    main()
