import os
import anthropic
import requests

# Configuration
ANTHROPIC_API_KEY = os.environ['ANTHROPIC_API_KEY']
GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
GITHUB_REPO = os.environ['GITHUB_REPOSITORY']
PR_NUMBER = os.environ.get('PR_NUMBER')
NOTION_TOKEN = os.environ.get('NOTION_TOKEN')
NOTION_DATABASE_ID = os.environ.get('NOTION_DATABASE_ID')

# Validate PR_NUMBER
if not PR_NUMBER or PR_NUMBER == '':
    print("❌ PR_NUMBER not set. This workflow must be triggered by a pull request.")
    exit(0)

def get_pr_details():
    """Fetch PR details and metadata"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls/{PR_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    response = requests.get(url, headers=headers)
    return response.json()

def get_pr_files():
    """Fetch all changed files in the PR"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls/{PR_NUMBER}/files"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    response = requests.get(url, headers=headers)
    data = response.json()
    
    if isinstance(data, dict):
        print(f"Warning: Unexpected response: {data}")
        return []
    
    return data

def get_pr_diff():
    """Get the unified diff for the PR"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls/{PR_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3.diff"
    }
    response = requests.get(url, headers=headers)
    return response.text[:4000]  # Limit to 4000 chars

def review_code_with_claude(pr_details, files, diff):
    """Use Claude to review the code changes"""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    
    # Prepare file summary
    file_summary = []
    for file in files[:5]:  # Limit to 5 files
        file_summary.append(f"- {file['filename']}: +{file['additions']} -{file['deletions']} lines")
    
    prompt = f"""You are a Senior Code Reviewer AI agent. Review this pull request and provide constructive feedback.

**PR Title:** {pr_details.get('title', 'Unknown')}
**Description:** {pr_details.get('body', 'No description provided')[:500]}

**Changed Files:**
{chr(10).join(file_summary)}

**Code Diff (sample):**
```
{diff}
```

**Your task:**
Provide a code review with:

1. **Overall Assessment** (Approve, Request Changes, or Comment)
2. **Code Quality** (readability, maintainability, best practices)
3. **Potential Issues** (bugs, edge cases, security concerns)
4. **Suggestions** (improvements, optimizations)
5. **Positive Feedback** (what's done well)

Be constructive and specific. Focus on:
- Logic errors or bugs
- Security vulnerabilities
- Performance issues
- Code style and readability
- Missing error handling
- Potential edge cases

Format your response as structured markdown with clear sections."""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2500,
        messages=[{"role": "user", "content": prompt}]
    )
    
    return message.content[0].text

def post_review_comment(pr_details, review):
    """Post review as a comment on the PR"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{PR_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    
    comment_body = f"""## 👨‍💻 PR Review Agent Analysis

{review}

---
**Note:** This is an automated review. Human approval still required for merge.

*Generated by PR Review Agent*"""
    
    response = requests.post(
        url,
        headers=headers,
        json={"body": comment_body}
    )
    
    if response.status_code == 201:
        print("✅ Review posted to GitHub")
    else:
        print(f"⚠️ Failed to post review: {response.status_code}")

def post_to_notion(pr_title, pr_number, review, pr_url):
    """Post review to Notion database"""
    if not NOTION_TOKEN or not NOTION_DATABASE_ID:
        print("⚠️ Notion credentials not configured, skipping Notion post")
        return
    
    headers = {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28"
    }
    
    # Truncate review if too long
    truncated_review = review[:1800] if len(review) > 1800 else review
    
    data = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Name": {
                "title": [{"text": {"content": f"PR Review: {pr_title[:80]}"}}]
            },
            "Agent Type": {
                "select": {"name": "PR Review"}
            },
            "Issue/PR Number": {
                "number": int(pr_number)
            },
            "Status": {
                "select": {"name": "Complete"}
            }
        },
        "children": [
            {
                "object": "block",
                "type": "heading_2",
                "heading_2": {
                    "rich_text": [{"type": "text", "text": {"content": "Code Review Report"}}]
                }
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [
                        {"type": "text", "text": {"content": "PR: "}},
                        {"type": "text", "text": {"content": pr_title, "link": {"url": pr_url}}}
                    ]
                }
            },
            {
                "object": "block",
                "type": "divider",
                "divider": {}
            },
            {
                "object": "block",
                "type": "paragraph",
                "paragraph": {
                    "rich_text": [{"type": "text", "text": {"content": truncated_review}}]
                }
            }
        ]
    }
    
    response = requests.post(
        "https://api.notion.com/v1/pages",
        headers=headers,
        json=data
    )
    
    if response.status_code == 200:
        print("✅ Posted to Notion successfully!")
    else:
        print(f"⚠️ Notion post failed: {response.status_code}")
        print(response.text)

def main():
    print(f"🤖 PR Review Agent starting for PR #{PR_NUMBER}...")
    
    # Get PR details
    pr_details = get_pr_details()
    pr_title = pr_details.get('title', 'Unknown PR')
    pr_url = pr_details.get('html_url', '')
    print(f"📝 Reviewing: {pr_title}")
    
    # Get changed files
    files = get_pr_files()
    if not files:
        print("⚠️ No files to review")
        return
    
    print(f"📂 Found {len(files)} changed files")
    
    # Get diff
    diff = get_pr_diff()
    
    # Review with Claude
    print("🔍 Analyzing code with Claude...")
    review = review_code_with_claude(pr_details, files, diff)
    print(f"✅ Review complete ({len(review)} characters)")
    
    # Post to GitHub
    post_review_comment(pr_details, review)
    
    # Post to Notion
    print("📝 Posting to Notion...")
    post_to_notion(pr_title, PR_NUMBER, review, pr_url)
    
    print("✅ PR Review Agent completed successfully!")

if __name__ == "__main__":
    main()
