import os
import anthropic
import requests

# Configuration
ANTHROPIC_API_KEY = os.environ['ANTHROPIC_API_KEY']
GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
GITHUB_REPO = os.environ['GITHUB_REPOSITORY']
PR_NUMBER = os.environ['PR_NUMBER']

def get_pr_changes():
    """Fetch PR file changes"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls/{PR_NUMBER}/files"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    response = requests.get(url, headers=headers)
    data = response.json()
    
    # Handle edge cases
    if isinstance(data, dict):
        print(f"Warning: Unexpected response format: {data}")
        return []
    
    return data

def generate_tests(changes):
    """Use Claude to generate test cases based on code changes"""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    
    # Get file contents
    files_content = []
    for file in changes[:3]:  # Limit to first 3 files
        if file['filename'].endswith('.py'):
            files_content.append(f"File: {file['filename']}\n{file.get('patch', '')}")
    
    if not files_content:
        print("No Python files to test")
        return None
    
    prompt = f"""You are a QA Engineer AI agent. Generate comprehensive pytest test cases for the following code changes.

**Code Changes:**
{chr(10).join(files_content)}

**Your task:**
1. Create pytest test cases covering:
   - Happy path scenarios
   - Edge cases
   - Error conditions
   - Boundary values

2. Use pytest fixtures where appropriate
3. Include clear test names and docstrings
4. Mock external dependencies if needed

Generate ONLY the Python test code, ready to save as a file. Include all necessary imports."""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=3000,
        messages=[{"role": "user", "content": prompt}]
    )
    
    return message.content[0].text

def save_tests(test_code):
    """Save generated tests to file"""
    os.makedirs('tests', exist_ok=True)
    
    # Clean up code block markers if present
    if '```python' in test_code:
        test_code = test_code.split('```python')[1].split('```')[0].strip()
    elif '```' in test_code:
        test_code = test_code.split('```')[1].split('```')[0].strip()
    
    with open('tests/test_generated.py', 'w') as f:
        f.write(test_code)
    
    print(f"✅ Tests saved to tests/test_generated.py")

def post_qa_analysis(test_summary):
    """Post QA analysis to PR"""
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{PR_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    
    body = f"""## 🧪 QA Agent Analysis

**Test Coverage Generated:**
{test_summary}

**Next Steps:**
- ✅ Automated tests have been generated
- 🔍 Review test cases for completeness
- 🚀 Tests will run automatically

---
*Generated by QA Agent*"""
    
    requests.post(url, headers=headers, json={"body": body})

def main():
    print(f"🤖 QA Agent starting for PR #{PR_NUMBER}...")
    
    # Get PR changes
    changes = get_pr_changes()
    
    # Check if we got valid data
    if not changes:
        print("⚠️ No changes found or error fetching PR")
        test_summary = "No files to analyze"
        post_qa_analysis(test_summary)
        return
    
    print(f"📝 Found {len(changes)} changed files")
    
    # Generate tests
    test_code = generate_tests(changes)
    
    if test_code:
        save_tests(test_code)
        test_summary = f"Generated comprehensive test suite ({len(test_code)} characters)"
        print(f"✅ {test_summary}")
    else:
        test_summary = "No Python files requiring tests"
        print(f"⚠️ {test_summary}")
    
    # Post analysis
    post_qa_analysis(test_summary)
    print("✅ QA Agent completed successfully!")

if __name__ == "__main__":
    main()
